words = ['if', 'else', 'for', 'while', 'break', 'continue', 'return', 'typedef', 'case', 'switch', 'auto', 'extern',
         'const', '#include', '#define']

types = ['void',
         'unsigned int',
         'unsigned char',
         'unsigned short int',
         'unsigned short',
         'unsigned long int',
         'unsigned long',
         'unsigned long long int',
         'unsigned long long',
         'unsigned float',
         'unsigned double',
         'unsigned',
         'int',
         'char',
         'short int',
         'short',
         'long int',
         'long',
         'long long int',
         'long long',
         'float',
         'double',
         'union',
         'struct']
