from PyQt5.Qsci import QsciLexerCPP, QsciLexerPython, QsciLexerBash, QsciLexerBatch, QsciLexerCSharp, QsciLexerJava, \
    QsciLexerJavaScript, QsciLexerMarkdown, QsciLexerHTML, QsciLexerJSON
from code_tab.autocomplition.abstract import CodeAutocompletionManager as AcMAbstract
from code_tab.autocomplition.c import CodeAutocompletionManager as AcMC

languages = {
    'c': {'lexer': QsciLexerCPP, 'files': '.c', 'other_files': '.h', 'autocompletion': AcMC, 'colors': {
        QsciLexerCPP.Identifier: 'Identifier',
        QsciLexerCPP.PreProcessor: 'Preprocessor',
        QsciLexerCPP.Comment: 'Comment',
        QsciLexerCPP.CommentLine: 'Comment',
        QsciLexerCPP.CommentDoc: 'Comment',
        QsciLexerCPP.Keyword: 'Keyword',
        QsciLexerCPP.Number: 'Number',
        QsciLexerCPP.Operator: 'Identifier',
        QsciLexerCPP.DoubleQuotedString: 'String',
        QsciLexerCPP.SingleQuotedString: 'String',
    }},
    'python': {'lexer': QsciLexerPython, 'files': '.py', 'autocompletion': AcMAbstract, 'colors': {
        QsciLexerPython.Identifier: 'Identifier',
        QsciLexerPython.Comment: 'Comment',
        QsciLexerPython.CommentBlock: 'Comment',
        QsciLexerPython.Keyword: 'Keyword',
        QsciLexerPython.Number: 'Number',
        QsciLexerPython.Operator: 'Identifier',
        QsciLexerPython.ClassName: 'Preprocessor',
        QsciLexerPython.Decorator: 'Preprocessor',
        QsciLexerPython.FunctionMethodName: 'Preprocessor',
        QsciLexerPython.DoubleQuotedString: 'String',
        QsciLexerPython.SingleQuotedString: 'String',
        QsciLexerPython.DoubleQuotedFString: 'String',
        QsciLexerPython.SingleQuotedFString: 'String',
        QsciLexerPython.TripleDoubleQuotedString: 'String',
        QsciLexerPython.TripleSingleQuotedString: 'String',
        QsciLexerPython.TripleDoubleQuotedFString: 'String',
        QsciLexerPython.TripleSingleQuotedFString: 'String',
    }},
    'c++': {'lexer': QsciLexerCPP, 'files': '.cpp', 'other_files': '.h', 'autocompletion': AcMAbstract},
    'bach': {'lexer': QsciLexerBash, 'files': '.sh', 'autocompletion': AcMAbstract, 'colors': {
        QsciLexerBash.Identifier: 'Identifier',
        QsciLexerBash.Operator: 'Identifier',
        QsciLexerBash.Number: 'Number',
        QsciLexerBash.Comment: 'Comment',
        QsciLexerBash.Keyword: 'Keyword',
        QsciLexerBash.DoubleQuotedString: 'String',
        QsciLexerBash.SingleQuotedString: 'String',
        QsciLexerBash.ParameterExpansion: 'Preprocessor',
        QsciLexerBash.Error: 'Preprocessor',
    }},
    'batch': {'lexer': QsciLexerBatch, 'files': 'bat', 'other_files': '.cmd', 'autocompletion': AcMAbstract, 'colors': {
        QsciLexerBatch.Keyword: 'Keyword',
        QsciLexerBatch.Comment: 'Comment',
        QsciLexerBatch.ExternalCommand: 'Preprocessor',
        QsciLexerBatch.Operator: 'Identifier',
        QsciLexerBatch.HideCommandChar: 'String',
        QsciLexerBatch.Variable: 'Number',
        QsciLexerBatch.Default: 'Identifier'
    }},
    'markdown': {'lexer': QsciLexerMarkdown, 'files': '.md', 'autocompletion': AcMAbstract, 'colors': {
        QsciLexerMarkdown.BlockQuote: 'Keyword',
        QsciLexerMarkdown.CodeBlock: 'Preprocessor',
        QsciLexerMarkdown.CodeBackticks: 'Preprocessor',
        QsciLexerMarkdown.CodeDoubleBackticks: 'Preprocessor',
        QsciLexerMarkdown.Header1: 'Keyword',
        QsciLexerMarkdown.Header2: 'Keyword',
        QsciLexerMarkdown.Header3: 'Keyword',
        QsciLexerMarkdown.Header4: 'Keyword',
        QsciLexerMarkdown.Header5: 'Keyword',
        QsciLexerMarkdown.Header6: 'Keyword',
        QsciLexerMarkdown.Link: 'String',
    }},
    'html': {'lexer': QsciLexerHTML, 'files': '.html', 'autocompletion': AcMAbstract},
    'json': {'lexer': QsciLexerJSON, 'files': '.json', 'autocompletion': AcMAbstract},
    'c#': {'lexer': QsciLexerCSharp},
    'java': {'lexer': QsciLexerJava},
    'javascript': {'lexer': QsciLexerJavaScript, 'files': '.js', 'autocompletion': AcMAbstract},
}
