name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          
          venv\Scripts\python -m pip install -r requirements.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
        run: |
          venv\Scripts\Activate.ps1
          python -m build.add_secrets

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm TestGenerator.spec

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build\setup.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGenerator_windows.exe
          path: dist\TestGeneratorSetup.exe

#  build-linux:
#    name: Build for Linux
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.11.3
#
#      - name: Install dependencies
#        run: |
#          python3.11 -m pip install -r requirements.txt
#          python3.11 -m pip install --upgrade pyinstaller==6.3.0
#
#      - name: Secrets
#        env:
#          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
#          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
#          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
#        run: |
#          python -m build.add_secrets
#
#      - name: Build by Pyinstaller
#        run: |
#          pyinstaller --noconfirm TestGenerator.spec
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: TestGenerator_linux
#          path: dist/TestGenerator

# ------------ LITE -------------

  build-windows-lite:
    name: Build for Windows - Lite
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1

          venv\Scripts\python -m pip install -r requirements-lite.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
          USE_WEB_ENGINE: False
          USE_TELEGRAM: False
        run: |
          venv\Scripts\Activate.ps1
          python -m build.add_secrets

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm TestGeneratorLite.spec

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build\setup-lite.iss
          options: /O+

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGeneratorLite_windows.exe
          path: dist\TestGeneratorSetup.exe

#  build-linux-lite:
#    name: Build for Linux - Lite
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.11.3
#
#      - name: Install dependencies
#        run: |
#          python3.11 -m pip install -r requirements.txt
#          python3.11 -m pip install --upgrade pyinstaller==6.3.0
#
#      - name: Secrets
#        env:
#          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
#          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
#          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
#        run: |
#          python -m build.add_secrets
#
#      - name: Build by Pyinstaller
#        run: |
#          pyinstaller --noconfirm TestGenerator.spec
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: TestGenerator_linux
#          path: dist/TestGenerator
