name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1
          
          venv\Scripts\python -m pip install -r requirements/windows.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
        run: |
          venv\Scripts\Activate.ps1
          python -m add_secrets

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm TestGenerator.spec

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build\setup.iss
          options: /O+

      - name: Upload release
        run: |
          venv\Scripts\Activate.ps1
          python upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGenerator_windows.exe
          path: dist\TestGeneratorSetup.exe

#  build-linux:
#    name: Build for Linux
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: 3.11
#
#      - name: Install dependencies
#        run: |
#          python3.11 -m pip install -r requirements.txt
#          python3.11 -m pip install --upgrade pyinstaller==6.3.0
#
#      - name: Secrets
#        env:
#          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
#          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
#          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
#        run: |
#          python -m add_secrets
#
#      - name: Build by Pyinstaller
#        run: |
#          pyinstaller --noconfirm TestGenerator.spec
#
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: TestGenerator_linux
#          path: dist/TestGenerator

# ------------ LITE -------------

  build-windows-lite:
    name: Build for Windows - Lite
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1

          venv\Scripts\python -m pip install -r requirements/windows-lite.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
          USE_WEB_ENGINE: False
          USE_TELEGRAM: False
        run: |
          venv\Scripts\Activate.ps1
          python -m add_secrets

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm TestGeneratorLite.spec

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build\setup-lite.iss
          options: /O+

      - name: Upload release
        env:
          BUILD_TYPE: Lite
        run: |
          venv\Scripts\Activate.ps1
          python upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGeneratorLite_windows
          path: dist\TestGeneratorSetup.exe

  build-linux-lite:
    name: Build for Linux - Lite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements/linux-lite.txt
          python3.11 -m pip install pymorphy3-dicts-ru
          ls venv/Lib/site-packages/pymorphy3_dicts_ru
          python3.11 -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
        run: |
          python -m add_secrets
          cd src
          python3 -c "print('version=', __import__('config').APP_VERSION, sep='')" >> $GITHUB_OUTPUT

      - name: Build by Pyinstaller
        run: |
          pyinstaller --noconfirm TestGeneratorLite.spec

      - name: Prepare DEP package
        run: |
          python3 create_debpkg.py

      - name: Create DEB package
        uses: jiro4989/build-deb-action@v3
        with:
          package: testgenerator
          package_root: dist/debpkg
          maintainer: SergeiKrivko
          version: ${{ steps.build.outputs.version }}
          arch: 'amd64'
          desc: 'TestGeneratorLite'

      - name: Upload release
        env:
          BUILD_TYPE: Lite
        run: |
          python3 upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGeneratorLite_linux
          path: testgenerator_${{ steps.build.outputs.version }}_amd64.deb

  build-macos-lite:
    name: Build for macOS - Lite
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m pip install -r requirements/linux-lite.txt
          python3.11 -m pip install pymorphy3-dicts-ru
          ls venv/Lib/site-packages/pymorphy3_dicts_ru
          python3.11 -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
        run: |
          python -m add_secrets

      - name: Build by Pyinstaller
        run: |
          pyinstaller --noconfirm TestGeneratorLite.spec
          rm -rf dist/TestGeneratorLite

      - name: Create installer
        uses: QQxiaoming/create-dmg-action@v0.0.2
        with:
          name: 'TestGenerator'
          srcdir: 'dist/TestGeneratorLite.app'

      - name: Upload release
        env:
          BUILD_TYPE: Lite
        run: |
          python3 upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGeneratorLite_macos.dmg
          path: TestGenerator.dmg
