name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\Activate.ps1

          venv\Scripts\python -m pip install -r requirements.txt
          venv\Scripts\python -m pip install --upgrade pyinstaller==6.3.0 Pillow

      - name: Secrets
        env:
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
          USE_WEB_ENGINE: False
        run: |
          venv\Scripts\Activate.ps1
          python -m add_secrets

      - name: Build by Pyinstaller
        run: |
          venv\Scripts\Activate.ps1
          venv\Scripts\pyinstaller --noconfirm TestGenerator.spec

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: build\setup.iss
          options: /O+

      - name: Upload release
        run: |
          venv\Scripts\Activate.ps1
          python upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGenerator_windows
          path: dist\TestGeneratorSetup.exe

  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install --upgrade pyinstaller==6.3.0 Pillow

      - name: Secrets
        id: secrets
        env:
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
          USE_WEB_ENGINE: False
        run: |
          source venv/bin/activate
          python3 -m add_secrets
          cd src
          python3 -c "print('version=', __import__('config').APP_VERSION, sep='')" >> $GITHUB_OUTPUT

      - name: Build by Pyinstaller
        run: |
          source venv/bin/activate
          pyinstaller --noconfirm TestGenerator.spec

      - name: Prepare DEP package
        run: |
          source venv/bin/activate
          python3 create_debpkg.py

      - name: Create DEB package
        uses: jiro4989/build-deb-action@v3
        with:
          package: testgenerator
          package_root: dist/debpkg
          maintainer: SergeiKrivko
          version: ${{ steps.secrets.outputs.version }}
          arch: 'amd64'
          desc: 'TestGenerator'

      - name: Upload release
        run: |
          source venv/bin/activate
          python3 upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGenerator_linux
          path: testgenerator_${{ steps.secrets.outputs.version }}_amd64.deb

  build-macos:
    name: Build for macOS
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install --upgrade pyinstaller==6.3.0

      - name: Secrets
        env:
          CONVERTIO_API_KEY: ${{ secrets.CONVERTIO_API_KEY }}
          USE_WEB_ENGINE: False
        run: |
          source venv/bin/activate
          python3 -m add_secrets

      - name: Build by Pyinstaller
        run: |
          source venv/bin/activate
          pyinstaller --noconfirm TestGenerator.spec
          rm -rf dist/TestGenerator

      - name: Create installer
        uses: QQxiaoming/create-dmg-action@v0.0.2
        with:
          name: 'TestGenerator'
          srcdir: 'dist/TestGenerator.app'

      - name: Upload release
        run: |
          source venv/bin/activate
          python3 upload_release.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TestGenerator_macos
          path: TestGenerator.dmg
